# Generated by Django 3.2.19 on 2023-08-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormfillingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=224)),
                ('last_name', models.CharField(max_length=224)),
                ('who_invited', models.CharField(max_length=244)),
                ('date_visit', models.DateField()),
                ('hear_about', models.CharField(max_length=224)),
                ('company_name', models.CharField(max_length=224)),
                ('Your_industry', models.CharField(max_length=255)),
                ('professional_classifiction', models.CharField(max_length=255)),
                ('Address1', models.CharField(max_length=255)),
                ('Address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=254)),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField(blank=True, null=True)),
                ('gst', models.CharField(blank=True, default='no data', max_length=224, null=True)),
                ('experience', models.CharField(max_length=254)),
                ('time_spend', models.CharField(max_length=254)),
                ('edu_background', models.CharField(max_length=254)),
                ('revoke_license', models.BooleanField(default=False)),
                ('primary_occupation', models.BooleanField(default=False)),
                ('commitment', models.BooleanField(default=False)),
                ('qualified_substitue', models.BooleanField(default=False)),
                ('bring_referral', models.BooleanField(default=True)),
                ('quantity_referral', models.IntegerField(default=0)),
                ('bkmember', models.BooleanField(default=False)),
                ('otherOrg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referralform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_firs_name', models.CharField(max_length=254)),
                ('ref_last_name', models.CharField(max_length=254)),
                ('ref_bussiness_name', models.CharField(blank=True, max_length=254, null=True)),
                ('ref_phone', models.IntegerField()),
                ('ref_email', models.EmailField(max_length=254)),
                ('ref_business_rel1', models.CharField(max_length=254)),
                ('formuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfillingapp.formfillinguser')),
            ],
        ),
    ]
